### ISSUE TITLE
NBT for currency drops

### ISSUE THREAD

**Issue by prplz** [aadnk/ExperienceMod#3] opened 2013-02-12 02:47 UTC
Hey I think it would probably be better to use protocol lib to attach an nbt tag to the item drops rather than using display name and uuid tracking, as seen at http://dev.bukkit.org/server-mods/protocollib/files/14-protocol-lib-2-0-0/ . I have noticed a few players managing to pick up the economy drops, and a custom nbt tag would be a much better solution. Also this would have the advantage of persisting across server restarts, which could be annoying for some users (imagine you drop a large sum of money and the server restart is in 2 minutes.. haha)

**Comment by aadnk** [comment] 2013-02-12 02:53
That is true - problem is, ever since since the Bukkit team introduced the ItemMeta system, it has become very difficult to reliably attach arbitrary data to item stacks. 

The problem is that whenever you read an item meta (getItemMeta) and write it back, CraftBukkit will _recreate_ the internal NbtTagCompount class by transferring only those meta values it understands. This means that any custom tags will be lost whenever a plugin (or Bukkit) modifies the item meta (possibly also when cloning).

But you can still use item meta to store information. In our case, I could probably use the "lore" section to store this information reliably, which would also survive a server restart. :)

**Comment by prplz** [comment] 2013-02-12 07:36
Ok, I was unaware of that. That really sucks :(

**Closed as completed** 2017-11-23 01:19 UTC
